### ISSUE TITLE
Send call for filling out the contact form for data contributors once users register

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_notifications#1]
After creating an account http://data.opendevelopmentmekong.net/user/register, users should receive an email indicating that they should fill pout the contact form exposed under https://opendevelopmentmekong.net/contribute-data/ otherwise they won't be able to contribute with data.

## Sub-tasks

- [x] @prustar will draft text to include in email
- [x] @acorbi will implement

**Comment by prustar** [comment]
Text for email response is below. The only issue with this is that we don't have any idea if that person has already registered or not as the two registration processes are separate. If you can't automate the 'name' field here just put something generic like 'Welcome to the Open Development Mekong Datahub'  

Dear [Name],

This notification is to acknowledge that you have successfully created an account on the Open Development Mekong CKAN Datahub. 

If you have not already done so, please complete the registration process by filling out a registration form located on our 'contribute data' page. The page provides some details about what it means to become a data contributor and a link to FAQs. As a new user we ask that you complete the registration form to provide us with information about yourself so that we can appropriately assign you to an organisation or create a new one specifically for your organisation. It also provides information about our 'terms of use' which you must agree to prior to contributing. 

All your information is kept private and confidential and will not be disclosed unless otherwise specified. 
We look forward to seeing your contributions shortly. 

Regards,
ODM Data Team
